name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]

jobs:
  WhiteSource-Prioritize:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: WhiteSource Prioritize Scan
        env:
          WS_APIKEY: ${{secrets.APIKEY}}
        run: |
          curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
          echo UA downloaded successfully
          WARFILE=$(find ./ -type f -wholename "*/target/*.war")
          export WS_ENABLEIMPACTANALYSIS=true
          export WS_REQUIREKNOWNSHA1=false
          export WS_RESOLVEALLDEPENDENCIES=false
          export WS_MAVEN_RESOLVEDEPENDENCIES=true
          export WS_MAVEN_AGGREGATEMODULES=true
          export WS_FILESYSTEMSCAN=false
          java -jar wss-unified-agent.jar -appPath $WARFILE -d ./ -product GH_${{ github.event.repository.name }} -project ${{ github.ref }}_Prioritize